dependencies:
  artemis:
    url: github.com/toitware/toit-artemis
    version: ^0.5.0
  dps368:
    url: github.com/Informaticore/toit-dps368
    version: ^1.1.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  ringbuffer:
    url: github.com/Informaticore/toit-ringbuffer
    version: ^1.0.1
