dependencies:
  artemis:
    url: github.com/toitware/toit-artemis
    version: ^0.8.3
  dps368:
    url: github.com/informaticore/toit-dps368
    version: ^1.1.1
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  rv-3028-c7:
    url: github.com/informaticore/toit-rv-3028-c7
    version: ^0.0.1
